steps:
  # Dockerイメージをビルド（Artifact Registry対応）
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/ai-diary/ai-diary",
        "./ai-diary",
      ]

  # Artifact Registryにプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "asia-northeast1-docker.pkg.dev/$PROJECT_ID/ai-diary/ai-diary"]

  # Cloud Runにデプロイ
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "ai-diary"
      - "--image"
      - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/ai-diary/ai-diary"
      - "--region"
      - "asia-northeast1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--add-cloudsql-instances"
      - "univac-aiagent:asia-northeast1:cloudsql-01"
      - "--set-env-vars"
      - "GEMINI_API_KEY=AIzaSyBINVVUZhQVP3IS1ht1RBxguS9ajibSq-c,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,DB_PASSWORD=TH8V+cqXJOPqRl3Ez4RAg+mQvnlkQmqh/r14epk2BT0=,DB_HOST=localhost,DB_PORT=3306,DB_NAME=default,DB_USER=default,TZ=Asia/Tokyo"

images:
  - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/ai-diary/ai-diary"

options:
  logging: CLOUD_LOGGING_ONLY
