steps:
# Dockerイメージをビルド
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai-diary', './ai-diary']

# DockerイメージをContainer Registryにプッシュ
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ai-diary']

# Cloud Runにデプロイ
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'ai-diary'
  - '--image'
  - 'gcr.io/$PROJECT_ID/ai-diary'
  - '--region'
  - 'asia-northeast1' # リージョンを東京に変更
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--source'
  - './ai-diary' # ソースディレクトリを指定

images:
- 'gcr.io/$PROJECT_ID/ai-diary'

options:
  logging: CLOUD_LOGGING_ONLY
