steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/ai-diary', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/ai-diary' ]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [ 'run', 'deploy', 'ai-diary', '--image', 'gcr.io/$PROJECT_ID/ai-diary', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated' ]
images:
- gcr.io/$PROJECT_ID/ai-diary
