version: '3.8'

services:
  email-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SENDGRID_API_KEY=dummy-api-key-for-testing
      - DEFAULT_FROM_EMAIL=noreply@localhost.com
      - DEFAULT_FROM_NAME=Docker Test System
    volumes:
      - .:/app
    working_dir: /app
    command: python local_server.py

  # テスト用のメール送信クライアント
  email-tester:
    build: .
    depends_on:
      - email-service
    environment:
      - FUNCTION_URL=http://email-service:8080
    volumes:
      - .:/app
    working_dir: /app
    command: python test_email.py http://email-service:8080
    profiles:
      - test
