steps:
  # Dockerイメージをビルド
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/db-connect-test/db-connect-test",
        ".",
      ]

  # Artifact Registryにプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "asia-northeast1-docker.pkg.dev/$PROJECT_ID/db-connect-test/db-connect-test"]

  # Cloud Runにデプロイ
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "db-connect-test"
      - "--image"
      - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/db-connect-test/db-connect-test"
      - "--region"
      - "asia-northeast1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--add-cloudsql-instances"
      - "univac-aiagent:asia-northeast1:cloudsql-01"
      - "--set-env-vars"
      - "GOOGLE_CLOUD_PROJECT=$PROJECT_ID,DB_HOST=localhost,DB_PORT=3306,DB_USER=default,DB_PASSWORD=TH8V+cqXJOPqRl3Ez4RAg+mQvnlkQmqh/r14epk2BT0=,DB_NAME=default,TZ=Asia/Tokyo"

images:
  - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/db-connect-test/db-connect-test"

options:
  logging: CLOUD_LOGGING_ONLY
